#------------------------------------------------------------------------------
# Cannlytics API OpenAPI Specification
# Authors: Keegan Skeate <https://github.com/keeganskeate>
# Created 4/23/2023
# Updated: 10/11/2024
# License: MIT License <https://github.com/cannlytics/cannlytics/blob/main/LICENSE>
#------------------------------------------------------------------------------
openapi: 1.0.1
info:
  title: Cannlytics API
  summary: Cannabis data and analytics.
description: The Cannlytics API allows users to interface with cannabis data and analytics.
termsOfService: https://docs.cannlytics.com/about/terms-of-service/
contact:
  name: Cannlytics Admin
  url: https://www.cannlytics.com/support
  email: admin@cannlytics.com
license:
  name: MIT
  url: https://github.com/cannlytics/cannlytics/blob/main/LICENSE
servers:
- url: https://cannlytics.com/api
  description: Public API
paths:
  /:
    get:
      operationId: base.index
      summary: Base API endpoint for users to discover an index of endpoints.
      responses:
        200:
          description: Successful operation

  #------------------------------------------------------------------------------
  # Functions
  #------------------------------------------------------------------------------

  # AI text to emoji.
  /search:
    post:
      operationId: api.search
      summary: Search various data types for specific queries.
      responses:
        200:
          description: Successful operation

  # Standardization.
  /standardize:
    post:
      operationId: api.standardize
      summary: Standardize product names, strain names, and product types.
      responses:
        200:
          description: Successful operation

  #------------------------------------------------------------------------------
  # Data
  #------------------------------------------------------------------------------

  # Compound data.
  /compounds/{id}:
    get:
      summary: Retrieve specific compound data by ID.
      operationId: api.compounds
      parameters:
        - name: id
          in: path
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Compound data for the given ID.

  # COA data.
  /coas/{id}:
    get:
      summary: Retrieve COA data.
      operationId: api.coas
      parameters:
        - name: license_number
          in: path
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of any COA data found.

  # License data.
  /licenses/{license_number}:
    get:
      operationId: api.licenses
      summary: Get licenses data.
      parameters:
        - name: license_number
          in: path
          required: false
          schema:
            type: string
  
  # Lab results data.
  /results/{id}:
    get:
      operationId: api.results
      summary: Get a product's lab test result data by `id`.
      parameters:
        - name: id
          in: path
          required: false
          schema:
            type: string

  # Strain data.
  /strains/{id}:
    get:
      operationId: api.strains
      summary: Get strain data by `id`.
      parameters:
        - name: id
          in: path
          required: false
          schema:
            type: string
  
  # Label data.
  /labels/{id}:
    get:
      operationId: api.labels
      summary: Get a user's label data by `id`.
      parameters:
        - name: id
          in: path
          required: false
          schema:
            type: string
  
  # Receipt data.
  /receipts/{id}:
    get:
      operationId: api.receipts
      summary: Get a user's receipt data by `id`.
      parameters:
        - name: id
          in: path
          required: false
          schema:
            type: string
  
  #------------------------------------------------------------------------------
  # Users
  #------------------------------------------------------------------------------

  # User data.
  /users/{user_id}:
    get:
      operationId: users.users
      summary: Get user data by user_id.
      parameters:
        - name: user_id
          in: path
          required: false
          schema:
            type: string

  # User consumption data.
  /users/{user_id}/consumption:
    get:
      operationId: users.users
      summary: Get user consumption data by user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
  
  # User spending data.
  /users/{user_id}/spending:
    get:
      operationId: users.users
      summary: Get user spending data by user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
  
  # User logs.
  /users/{user_id}/logs/{log_id}:
    get:
      operationId: settings.logs
      summary: Get user log data by user_id and log_id.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: log_id
          in: path
          required: false
          schema:
            type: string
  
  # User settings.
  /users/{user_id}/settings:
    get:
      operationId: users.users
      summary: Get user settings by user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string

  #------------------------------------------------------------------------------
  # Metrc
  #------------------------------------------------------------------------------

  # Add Metrc API key.
  /metrc/admin/add-key:
    post:
      operationId: api.metrc.add_metrc_user_api_key
      summary: Add a Metrc user API key.

  # Delete Metrc API key.
  /metrc/admin/delete-key:
    delete:
      operationId: api.metrc.delete_metrc_user_api_key
      summary: Delete a Metrc user API key.

  # Batches.
  /metrc/batches/{batch_id}:
    get:
      operationId: api.metrc.batches
      summary: Retrieve a specific batch by ID.
      parameters:
        - name: batch_id
          in: path
          required: false
          schema:
            type: string

  # Deliveries.
  /metrc/deliveries/{delivery_id}:
    get:
      operationId: api.metrc.deliveries
      summary: Retrieve a specific delivery by ID.
      parameters:
        - name: delivery_id
          in: path
          required: false
          schema:
            type: string

  # Employees.
  /metrc/employees/{employee_id}:
    get:
      operationId: api.metrc.employees
      summary: Retrieve a specific employee by ID.
      parameters:
        - name: employee_id
          in: path
          required: false
          schema:
            type: string

  # Facilities.
  /metrc/facilities/{facility_id}:
    get:
      operationId: api.metrc.facilities
      summary: Retrieve a specific facility by ID.
      parameters:
        - name: facility_id
          in: path
          required: false
          schema:
            type: string

  # Harvests.
  /metrc/harvests/{harvest_id}:
    get:
      operationId: api.metrc.harvests
      summary: Retrieve a specific harvest by ID.
      parameters:
        - name: harvest_id
          in: path
          required: false
          schema:
            type: string

  # Items.
  /metrc/items/{item_id}:
    get:
      operationId: api.metrc.items
      summary: Retrieve a specific item by ID.
      parameters:
        - name: item_id
          in: path
          required: false
          schema:
            type: string

  # Locations.
  /metrc/locations/{area_id}:
    get:
      operationId: api.metrc.locations
      summary: Retrieve a specific location by ID.
      parameters:
        - name: area_id
          in: path
          required: false
          schema:
            type: string

  # Packages.
  /metrc/packages/{package_id}:
    get:
      operationId: api.metrc.packages
      summary: Retrieve a specific package by ID.
      parameters:
        - name: package_id
          in: path
          required: false
          schema:
            type: string

  # Patients.
  /metrc/patients/{patient_id}:
    get:
      operationId: api.metrc.patients
      summary: Retrieve a specific patient by ID.
      parameters:
        - name: patient_id
          in: path
          required: false
          schema:
            type: string

  # Plants.
  /metrc/plants/{plant_id}:
    get:
      operationId: api.metrc.plants
      summary: Retrieve a specific plant by ID.
      parameters:
        - name: plant_id
          in: path
          required: false
          schema:
            type: string

  # Tests.
  /metrc/tests/{test_id}:
    get:
      operationId: api.metrc.lab_tests
      summary: Retrieve a specific lab test by ID.
      parameters:
        - name: test_id
          in: path
          required: false
          schema:
            type: string

  # Test COAs.
  /metrc/tests/{test_id}/{coa_id}:
    get:
      operationId: api.metrc.lab_tests
      summary: Retrieve a specific lab test by test ID and COA ID.
      parameters:
        - name: test_id
          in: path
          required: true
          schema:
            type: string
        - name: coa_id
          in: path
          required: true
          schema:
            type: string

  # Sales.
  /metrc/sales/{sale_id}:
    get:
      operationId: api.metrc.sales
      summary: Retrieve a specific sale by ID.
      parameters:
        - name: sale_id
          in: path
          required: false
          schema:
            type: string

  # Transactions.
  /metrc/transactions/{start}/{end}:
    get:
      operationId: api.metrc.transactions
      summary: Retrieve transactions between a specific date range.
      parameters:
        - name: start
          in: path
          required: false
          schema:
            type: string
        - name: end
          in: path
          required: false
          schema:
            type: string

  # Strains.
  /metrc/strains/{strain_id}:
    get:
      operationId: api.metrc.strains
      summary: Retrieve a specific strain by ID.
      parameters:
        - name: strain_id
          in: path
          required: false
          schema:
            type: string

  # Transfer templates.
  /metrc/transfers/templates/{template_id}:
    get:
      operationId: api.metrc.transfer_templates
      summary: Retrieve a specific transfer template by ID.
      parameters:
        - name: template_id
          in: path
          required: false
          schema:
            type: string

  # Transfers.
  /metrc/transfers/{transfer_id}:
    get:
      operationId: api.metrc.transfers
      summary: Retrieve a specific transfer by ID.
      parameters:
        - name: transfer_id
          in: path
          required: false
          schema:
            type: string

  # Drivers.
  /metrc/drivers/{driver_id}:
    get:
      operationId: api.metrc.drivers
      summary: Retrieve a specific driver by ID.
      parameters:
        - name: driver_id
          in: path
          required: false
          schema:
            type: string

  # Vehicles.
  /metrc/vehicles/{vehicle_id}:
    get:
      operationId: api.metrc.vehicles
      summary: Retrieve a specific vehicle by ID.
      parameters:
        - name: vehicle_id
          in: path
          required: false
          schema:
            type: string

  # Types.
  /metrc/types/{type_id}:
    get:
      operationId: api.metrc.types
      summary: Retrieve Metrc types.
      parameters:
        - name: type_id
          in: path
          required: true
          schema:
            type: string
